### PR TITLE
Migrate to Swift 4 and iPhone X Support

### PR DESCRIPTION
**Pull request by tiagomartinho**
Hello @andreamazz!

This is an huge PR 😄 I struggled to do things incrementally.

I migrated the app to the latest version of Swift and added support for the iPhone X.

I had to replace the calendar dependency and now it shows a red marker when the goal is not met and blue when it was. I also saw that in the app in the App Store is possible to add a gulp to a previous day, however I didn't found this in the project.

The test pass, and I manually tested the app, however I'm not full confident everything works as expected. It would be nice if you could take a look.

What do you think?

### CODE REVIEW

**Comment by andreamazz** [comment]
@tiagomartinho 
whoa, that's pretty awesome, I really appreciate it. I'll take a look at everything as soon as possible. 👍

**Comment by andreamazz** [comment]
Hey @tiagomartinho 
the merge is nightmare-ish:
https://d.pr/i/PPTMxv
I'll have to merge it by hand.

**Comment by tiagomartinho** [comment]
Ok @andreamazz, let me know if I can help with anything! 

I also saw that the CI was failing and also passing when it was failing as well.

**Comment by andreamazz** [comment]
Hi @tiagomartinho 
The updates are up, there are still a couple of things to fix (I have to double check the safe areas and update the icons), but other than that, it should be fine. 
Thank you for your contribution, I really appreciate it. 
 I've added you to the contributor's section in the readme since I can't merge this.

👍

**Comment by tiagomartinho** [comment]
Grazie @andreamazz!

**Pull request closed without merging**
