### PR TITLE
German localization for gulps

### PR DESCRIPTION
**Pull request by micheld93**
Hi, 
What about a german localization for gulps?

I downloaded the code and tried to find the things that have to be translated. 
See my german translation below:

/\* 
  Localizable.strings (German)
  Gulps

  Created by Michel Döhring on 23.10.15.
  Copyright (c) 2015 Fancy Pixel. All rights reserved.
*/

/\* Globals */
"notification text" = "Wasser trinken nicht vergessen!";
"Liters" = "Liter";
"Ounces" = "Unzen";

/\* Main */
"drink title" = "Trinken!";
"undo poptip" = "Zum Rückgängigmachen bitte tippen";
"undo title" = "Rückgängig";
"undo message" = "Letzte Aktion rückgängig machen?";
"No" = "Nein";
"Yes" = "Ja";

/\* Calendar */
"progress title" = "Mein Verlauf";
"share poptip" = "Hier kann der Verlauf eingesehen werden";
"share text" = "Bleib gesund! Ich habe %d %@ Wasser in %d Tagen getrunken. https://goo.gl/reTyQU";
"unit format" = "%@ getrunken in";
"goal met" = "Ziel erreicht!";

/\* Settings */
"settings title" = "Einstellungen";
"hours" = "Stunden";
"hour" = "Stunde";
"unit of measure title" = "Einheit:";
"from:" = "Von:";
"to:" = "Bis:";
"every:" = "Intervall:";

/\* Today ext */
"way to go" = "Way to go!";
"today extension format" = "Heute bereits %@ %@ gedrunken (%@ des Tages-Ziels)";
"confirm" = "Korrekt";
"never mind" = "Falsch";

/\* WatchKit */
"daily goal:" = "TÄGLICHES ZIEL: ";

/\* HealthKit */
"health.poptip" = "Der Apple Health export kann in den Einstellungen aktiviert werden";

### CODE REVIEW

**Comment by andreamazz** [comment]
Hi @micheld93 
Thank you so much for this. The app has a bunch of other strings to translate though. I collected them all into a public accessible and writable spreadsheet [here](https://docs.google.com/spreadsheets/d/1vh_b1VNcrsiV3mtwOY1V7tW0LR18wHoE1xCMuigc8pg/edit?usp=sharing). 
If you are willing you can modify that file, I'll merge the files in the next release. 
Thanks again for your support :+1:

**Comment by micheld93** [comment]
Hi @andreamazz 
Nice to hear that it is appreciated. In this spreadsheet above I translated all phrases into german. Hope it comes soon via an update to the App Store ...:-)

**Comment by andreamazz** [comment]
Thanks @micheld93, this is pretty awesome! 
I'll include the new languages in the next update (that should be version 1.8, version 1.7 is currently in review). 
Thanks :+1:

**Comment by micheld93** [comment]
Absolutely awesome. Like to see it in the future...If there are some mistakes in the layout (perhaps some sentences are a bit too long or something like that) and I recognized them, I will edit it in the spreadsheet above.  And, of course, I write here again to inform you....:-)

**Pull request closed without merging**
